package parser

const (
	TStruct    = "struct"
	TInterface = "interface"
	TSlice     = "slice"
	TArray     = "array"
	TFunc      = "func"
	TChan      = "chan"
	TMap       = "map"
	TInt       = "int"
	TInt8      = "int8"
	TInt16     = "int16"
	TInt32     = "int32"
	TInt64     = "int64"
	TUint      = "uint"
	TUint8     = "uint8"
	TUint16    = "uint16"
	TUint32    = "uint32"
	TUint64    = "uint64"
	TFloat32   = "float32"
	TFloat64   = "float64"
	TString    = "string"
	TBool      = "bool"
	TByte      = "byte"
	TRune      = "rune"
	TUintptr   = "uintptr"
	TAny       = "any"
	TError     = "error"
)
