package typescript_axios

const baseTpl = `
/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Mix Openapi Generator https://github.com/gozelle/mix)
 *
 * The version of the OpenAPI document: 3.0.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://mix.gozelle.io).
 * Do not edit the class manually.
 */

// Some imports not used depending on template conditions
// @ts-ignore
import axios, {AxiosInstance, AxiosRequestConfig} from 'axios';

export const BASE_PATH = "http://localhost".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface RequestArgs
 */
export interface RequestArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    public client: AxiosInstance;
    constructor(protected config: AxiosRequestConfig) {
        this.client = axios.create(config)
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError" = "RequiredError";

    constructor(public field: string, msg?: string) {
        super(msg);
    }
}
`
